### ISSUE TITLE
Nullable OneToOneFields

### ISSUE THREAD

**Issue by mitchellpalmer** [microsoft/mssql-django#59] opened 2021-08-03 08:21 UTC
Due to MS-SQL not properly implementing the ANSI SQL specification on this issue, multiple nulls in a column violate a Unique constraint. This means it is practically impossible to create nullable OneToOneFields in Django. There appears to be a possible fix -- https://stackoverflow.com/a/767702.

I am going to try to implement a fix for my own use case and will share it once I have done so, but I thought I would post an issue in case someone has solved this issue in the past or has any tips.

**Comment by mitchellpalmer** [comment] 2021-08-03 08:27
Digging into the source code, it looks like this fix is already present in schema.py, but for some reason is not trigger for OneToOneField relationships. I will investigate further.

**Comment by absci** [comment] 2021-08-05 03:15
Thanks for open this issue, feel free to post any of your discoveries here.

**Comment by jmah8** [comment] 2022-03-22 17:07
I was looking through some old issues and came across this, but I could not reproduce this problem using the following models and then saving two Restaurants with null place.
```
class Place(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=80)


class Restaurant(models.Model):
    place = models.OneToOneField(
        Place,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    serves_hot_dogs = models.BooleanField(default=False)
    serves_pizza = models.BooleanField(default=False)

Restaurant(place=None).save()
Restaurant(place=None).save()
```
A nullable OneToOneField with multiple nulls in a column seems to work.

**Comment by jmah8** [comment] 2022-03-30 18:31
I am going to close this issue for now but feel free to reopen it if there are still issues.

**Closed by jmah8** 2022-03-30 18:31 UTC
