### ISSUE TITLE
ImportError: compiler.py line 10 

### ISSUE THREAD

**Issue by Eliuhepher** [microsoft/mssql-django#215] opened 2022-12-17 17:04 UTC
in version 1.2 throws an error 

compiler.py line 10 
cannot import name 'Random'  from django.db.models.functions

If I uninstall 1.2 and return to 1.1.3 the issue is gone.

**Comment by khanhmaibui** [comment] 2022-12-20 18:41
Hi @Eliuhepher, could you provide some more details regarding the command you are trying to run, your configuration and software version (such as Python and Django versions)?

**Comment by firula** [comment] 2022-12-21 14:44
The problem is this file

[compiler.py](https://github.com/microsoft/mssql-django/blob/1.2/mssql/compiler.py#L11)

trying to load the class Random, which does not exist before Django 4.1.4 

[Fixed #32060 -- Added Random database function. #13473](https://github.com/django/django/pull/13473/commits)

So it is failing in previous versions of Django.

**Comment by khanhmaibui** [comment] 2022-12-21 18:34
Hi @firula, thanks for the comment. The class Random was actually released in Django 3.2. Here's a link to the Django documentation on that: https://docs.djangoproject.com/en/3.2/releases/3.2/

**Closed** 2023-07-28 19:12 UTC
