### ISSUE TITLE
Conversion failed when converting date and/or time from character string.

### ISSUE THREAD

**Issue by powelleric** [microsoft/mssql-django#266] opened 2023-05-04 19:21 UTC
**Software versions**
* Django: 4.18
* mssql-django: 1.2
* python: 3.10
* SQL Server:
* OS:

The bad SQL is 

```
('SELECT DISTINCT CONVERT(datetime2, CONVERT(varchar(4), '
 "[MonthlyUserSummary].[Month]) + '/01/01') AS [datetimefield] FROM "
 '[MonthlyUserSummary] WHERE [MonthlyUserSummary].[Month] IS NOT NULL ORDER BY '
 '[datetimefield] ASC OFFSET 0 ROWS')
```

For me `CONVERT(varchar(4), [MonthlyUserSummary].[Month])` results in a string like 'Apr '.  Appending that to '01/01' results in 'Apr /01/01'.  That causes the error about "Conversion failed":

```
select convert(datetime2, 'Apr /01/01')
```

That sql is coming from date_trunc_sql()

EDIT:

I downgraded to django 4.0.7 and mssql 1.1.3.  That fixed the issue.  It used:

```
"SELECT DISTINCT CONVERT(datetime2, CONVERT(varchar, DATEPART(year,   [MonthlyUserSummary].[Month])) + '/01/01') AS [datetimefield] 
FROM [MonthlyUserSummary] 
WHERE [MonthlyUserSummary].[Month] IS NOT NULL ORDER BY [datetimefield] ASC OFFSET 0 ROWS
```

**Comment by mShan0** [comment] 2023-05-08 20:29
Hi @powelleric, is it possible to provide steps to reproduce this?

**Comment by powelleric** [comment] 2023-05-17 16:51
I don't have a working example, but this code runs as a results of using the `date_hierarchy` option with Django admin.  It is trying to figure out all the different months in which records are observed to put links that the user can filter with. (In other words, v1.2 breaks any admin pages for models using that option.) 

```
class MonthlyUserSummaryAdmin(admin.ModelAdmin):

    date_hierarchy = "month"
    list_display = (
        "user_id",
        "email",
        "first_name",
        "last_name",
        "month",
        "login_count",
    )
    ordering = ["-month"]
```

**Comment by khanhmaibui** [comment] 2023-06-12 19:29
Hi @powelleric, can I see your models.py?

**Comment by powelleric** [comment] 2023-06-12 21:26
```
class MonthlyUserSummary(models.Model):
    """
    Summary of user activity for a given month.
    """

    user_id = models.ForeignKey(MyUser, to_field="id", primary_key=True, db_column='UserId', on_delete=models.DO_NOTHING)
    email = models.CharField(db_column='Username', max_length=MAXCHAR)
    first_name = models.CharField(db_column='FirstName', max_length=MAXCHAR)
    last_name = models.CharField(db_column='LastName', max_length=MAXCHAR)
    month = models.DateTimeField(db_column='Month')
    month_rank = models.IntegerField(db_column='MonthRank')
    login_count = models.IntegerField(db_column='LoginCount')
    is_new_user = models.BooleanField(db_column='IsNewUser')

    class Meta:
        managed = False
        db_table = 'MonthlyUserSummary'
```

**Comment by khanhmaibui** [comment] 2023-06-12 23:44
Hi @powelleric, can I know what SQL Server you are using?

**Comment by powelleric** [comment] 2023-06-13 00:24
I'm on AWS RDS.  It says:
Engine version
15.00.4073.23.v1
SQL Server Express Edition

**Comment by khanhmaibui** [comment] 2023-06-15 22:46
Hi @powelleric, we have been trying to reproduce this issue locally but we're still not able to. Can you provide us detailed steps to reproduce, including any additional configurations you may have?

**Comment by powelleric** [comment] 2023-06-17 16:06
I'm not sure that I have time right now to do that.

Just to be clear I did point out the exact function that contains the bug.
Are we in agreement that this function does not produce valid SQL?

I guess that there is no test coverage for this function is there?

**Comment by mShan0** [comment] 2023-06-19 17:16
No, the SQL is producing the right output for us. That's why we're asking for detailed repro steps.

We made this change because there was additional test coverage added. You can check for yourself.
https://github.com/django/django/blob/main/tests/db_functions/datetime/test_extract_trunc.py

**Comment by powelleric** [comment] 2023-06-20 14:53
I'm not sure we are on the same page.  I'm happy to just close this issue because I don't feel like this is progressing.  
If you say it is tested and working for you, then there is nothing else to be done.
I see this repo is maintained by Microsoft, therefore, I would be happy to continue if you offer a bug bounty.

**Comment by brucegibbins** [comment] 2023-07-28 09:28
Hello, I'd like to ask if this issue could be reopened? I am not sure that I can produce exact details on how to reproduce via test script. But will do my best.

Our setup is very similar. 

**Django v4.2.3**
**SQL Server Express v15.0.2000.5 (for local dev purposes). Issue also occurs with SQL Server 2019**
**Python v3.11.4**
**mssql-django v1.3**
**driver: SQL Server Native Client 11.0**
**Django Setting USE_TZ = False**

In our case I believe the issue is that the table column being used for Filtering and date hierarchy is a **datetime** type rather than just a **date** type. The SQL being generated is malformed in that in our case it generates the following which if pasted into SSMS for example will generate this error. In this case the **[B2BEvent].[CreatedOn]** column is defined as **datetime**. Any of the following samples will produce the desired result.

**fails**
`SELECT DISTINCT CONVERT(datetime2, CONVERT(varchar(4), [B2BEvent].[CreatedOn]) + '/01/01') AS [datetimefield] FROM [B2BEvent] WHERE [B2BEvent].[CreatedOn] IS NOT NULL ORDER BY 1 ASC`

**works**
`SELECT DISTINCT CONVERT(datetime2, CONVERT(varchar(4), CAST([B2BEvent].[CreatedOn] AS Date)) + '/01/01') AS [datetimefield] FROM [B2BEvent] WHERE [B2BEvent].[CreatedOn] IS NOT NULL ORDER BY 1 ASC`

`SELECT DISTINCT CONVERT(datetime2, CONVERT(varchar(4), [B2BEvent].[CreatedOn], 112) + '/01/01') AS [datetimefield] FROM [B2BEvent] WHERE [B2BEvent].[CreatedOn] IS NOT NULL ORDER BY 1 ASC`

`SELECT DISTINCT CONVERT(datetime2, CONVERT(varchar(4), CONVERT(date, [B2BEvent].[CreatedOn])) + '/01/01') AS [datetimefield] FROM [B2BEvent] WHERE [B2BEvent].[CreatedOn] IS NOT NULL ORDER BY 1 ASC`

The following debug trace indicates the code and the local variables.
<img width="1401" alt="mssql" src="https://github.com/microsoft/mssql-django/assets/16873240/5b22ae0a-5457-4bd3-aff9-73bca26c1ac0">

Thanks for your consideration.

**Comment by khanhmaibui** [comment] 2023-07-28 19:14
Thank you for the details. We'll look further into this.

**Comment by khanhmaibui** [comment] 2023-08-18 21:14
Hi, I have opened a PR to fix this issue. Can you try that to see if that works?

**Comment by caramdache** [comment] 2023-08-24 13:33
> Hi, I have opened a PR to fix this issue. Can you try that to see if that works?

Yes it does work perfectly, thanks!

**Comment by powelleric** [comment] 2023-08-24 14:59
> Hi, I have opened a PR to fix this issue. Can you try that to see if that works?

I have not tested it, but I looked at the PR and it looks very promising.  It alters the date_trunc_sql function that was the issue for me.  I will test it as soon as it is released.   Thanks for your help!

**Comment by mShan0** [comment] 2023-08-24 19:39
Merged the fix into dev!

**Closed by mShan0** 2023-08-24 19:39 UTC

**Comment by powelleric** [comment] 2023-11-07 03:13
Just pulled the dev branch and can confirm that this fixes the issue.  Thank you.  Looking forward to the next release.
