### ISSUE TITLE
Insert on tables with triggers fails in 1.1.3

### ISSUE THREAD

**Issue by timnyborg** [microsoft/mssql-django#130] opened 2022-05-09 11:29 UTC
As of 1.1.3, when I attempt to insert rows on tables with triggers through a standard model.save(), I receive the error "The target table 'email' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause."

I assume this is due to https://github.com/microsoft/mssql-django/pull/107, which has replaced the SCOPE_IDENTITY with an OUTPUT INSERTED.id

**Comment by jmah8** [comment] 2022-05-10 22:06
Thanks for the report. I can reproduce this issue.

**Comment by jmah8** [comment] 2022-07-21 20:44
Closing this issue since a workaround for this error was introduced in PR #158. If there is a trigger in a database you can add "has_trigger": True to the OPTIONS dictionary eg:
```    
DATABASES = {
        'default': {
            'ENGINE': 'mssql',
	     ...
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
		'has_trigger': True,
            },
        },
    }
```
It is false by default so if other databases don't have triggers nothing needs to be added. This workaround prevents returning rows from bulk insert when `has_trigger = True` though.

**Closed by jmah8** 2022-07-21 20:44 UTC

**Comment by jmah8** [comment] 2022-08-03 19:57
Some updates regarding this issue, after some internal discussion we decided to change the workaround so that inserting into tables with triggers follows the behaviour from v1.1.2 (works by default). So instead of `has_trigger` we replaced it with `return_rows_bulk_insert` as an option in the `OPTIONS` dictionary. It is false by default and when false it allows for inserting into tables with triggers with no errors but prevents returning ids from bulk insert. The PR that has these changes is PR #161 and will be included in the next release.

**Comment by adriennefranke** [comment] 2022-09-01 18:52
@jmah8 Do you have a date in mind when the next release will come?
