### ISSUE TITLE
Database migrations previously done with version 1.0 are not detected when using 1.1 or 1.1.1

### ISSUE THREAD

**Issue by maxschnettler** [microsoft/mssql-django#81] opened 2021-12-13 17:21 UTC
After updating to version 1.1 or 1.1.1 (without changing any other parameter), Django does not detect the already existing migrations in my database. These migrations were done using version 1.0. 

I am using Django 3.2.8, running locally on macOS 11.6, Azure SQL database with a user-defined schema (default schema of the corresponding database user --> not explicitly defined or mentioned in my Django settings).

When starting the Django debug server, the warning about unapplied migrations appears:
```
 % python manage.py runserver       
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 20 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, <my-own-data-model>, sessions.
Run 'python manage.py migrate' to apply them.
December 13, 2021 - 14:34:15
Django version 3.2.8, using settings '<my-project-name>.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
``` 

The app itself works, I can log into my app and it seems to function properly with the existing database migrations. However, when I try to migrate the changes, the following exception occurs due to the already existing object `django_migrations`:
```
django.db.utils.ProgrammingError: 
('42S01', "[42S01] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There is already an object named 'django_migrations' in the database. (2714) (SQLExecDirectW)")
```

Is this an issue of the new version, or am I missing some parameters I need to update? Do you have any recommended fix or at least a workaround?

**Comment by absci** [comment] 2021-12-16 00:28
This is a little weird, I couldn't reproduce it. Back up your migration files first. Try to run `python manage.py showmigrations`, and check through your migration files with your database, see if those migrations actually applied or not. If those migrations have been applied (the table and data exist in the database), then you could do `python manage.py migrate --fake <app> <migration-number>` to mark them applied.

**Comment by manuel-rdco** [comment] 2021-12-17 23:17
Hello.
Maybe my case could throw some light:
I was suffering the same symptoms as maxschnettler so I made a complete new install in a pod in Docker, using pip install mssql-django==1.0rc1, then made a migrate. Once everything was working again, I started debugging with level DEBUG to see the sql sentences being launched. Then I executed a manage.py showmigrations and the existing migrations in the database were detected, everything normal. The query was:
QUERY = 'SELECT TABLE_NAME, TABLE_TYPE FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = SCHEMA_NAME()'
Then, I did only a pip install mssql-django==1.1 and the repeated the showmigrations command. It worked and the query was the same, Ok. Then I did only a pip install mssql-django==1.1.0 and the showmigrations showed no migrations this time, but the interesting thing is that the query was now:
QUERY = "SELECT TABLE_NAME, TABLE_TYPE FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo'"
i.e. now instead of using the user’s default schema that I have, it is using dbo.

There might be an error somewhere so the user's default schema is not being taken into account. I downgraded to mssql-django==1.1 for the moment. It is the last one which is working in my case.

Thank you.

**Comment by absci** [comment] 2021-12-18 01:11
> Hello. Maybe my case could throw some light: I was suffering the same symptoms as maxschnettler so I made a complete new install in a pod in Docker, using pip install mssql-django==1.0rc1, then made a migrate. Once everything was working again, I started debugging with level DEBUG to see the sql sentences being launched. Then I executed a manage.py showmigrations and the existing migrations in the database were detected, everything normal. The query was: QUERY = 'SELECT TABLE_NAME, TABLE_TYPE FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = SCHEMA_NAME()' Then, I did only a pip install mssql-django==1.1 and the repeated the showmigrations command. It worked and the query was the same, Ok. Then I did only a pip install mssql-django==1.1.0 and the showmigrations showed no migrations this time, but the interesting thing is that the query was now: QUERY = "SELECT TABLE_NAME, TABLE_TYPE FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo'" i.e. now instead of using the user’s default schema that I have, it is using dbo.
> 
> There might be an error somewhere so the user's default schema is not being taken into account. I downgraded to mssql-django==1.1 for the moment. It is the last one which is working in my case.
> 
> Thank you.

Thanks for the detailed information, I think I know where the problem is. The fix will come soon.

**Comment by manuel-rdco** [comment] 2021-12-18 15:29
All right. Thank you very much. 

Just for clarification to other possible readers with the same problem: it appears that I made a mistake while writing the version numbers: the last working version is 1.0, which seems Ok, but 1.1 and 1.1.1 don't work for me (just as @maxschnettler said).

Thanks. Bye.

**Comment by kenshaw** [comment] 2022-01-07 02:32
Have the same issue. Any progress yet?

**Comment by absci** [comment] 2022-01-07 18:25
> Have the same issue. Any progress yet?

This should be fixed in the dev branch now, the next release will be at the end of January.

**Closed** 2022-02-17 17:00 UTC
