### ISSUE TITLE
Migration renaming a field fails

### ISSUE THREAD

**Issue by verneris** [microsoft/mssql-django#67] opened 2021-09-13 14:57 UTC
Migration renaming a field fails on mssql-django version 1.0 but succeeds on 1.0rc1. Tested on both Django 2.2.17 and 3.2.7. The issue is probably related to [commit](https://github.com/microsoft/mssql-django/commit/76d8a92faacb58744f29972bd3afa9e9d149ce38) which removed the index deletion before column rename.

Migration which creates the field:
```
migrations.AddField(
    model_name='transaction',
    name='conf_first_distribution_date',
    field=models.OneToOneField(blank=True, null=True, default=None, on_delete=django.db.models.deletion.SET_NULL, related_name='first_distribution_date_transaction', to='transaction.DateConfig'),
)
```

Migration which tries to rename the field but fails:
```
migrations.RenameField(
    model_name='transaction',
    old_name='conf_first_distribution_date',
    new_name='first_distribution_date',
)
```

Output:
```
   Applying transaction.0016_auto_20200424_1103...Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
     return self.cursor.execute(sql, params)
   File "/usr/local/lib/python3.8/site-packages/mssql/base.py", line 567, in execute
     return self.cursor.execute(sql, params)
 pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The index 'transaction_transaction_conf_first_distribution_date_id_76f3b97f_uniq' is dependent on column 'conf_first_distribution_date_id'. (5074) (SQLExecDirectW)")
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "dev_manage.py", line 15, in <module>
     execute_from_command_line(sys.argv)
   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
     utility.execute()
   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
     self.execute(*args, **cmd_options)
   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
     output = self.handle(*args, **options)
   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
     res = handle_func(*args, **kwargs)
   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
     post_migrate_state = executor.migrate(
   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
     state = migration.apply(state, schema_editor)
   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 350, in database_forwards
     schema_editor.alter_field(
   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 608, in alter_field
     self._alter_field(model, old_field, new_field, old_type, new_type,
   File "/usr/local/lib/python3.8/site-packages/mssql/schema.py", line 348, in _alter_field
     self.execute(self._rename_field_sql(model._meta.db_table, old_field, new_field, new_type))
   File "/usr/local/lib/python3.8/site-packages/mssql/schema.py", line 880, in execute
     cursor.execute(sql, params)
   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
     return super().execute(sql, params)
   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
     return executor(sql, params, many, context)
   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
     return self.cursor.execute(sql, params)
   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
     raise dj_exc_value.with_traceback(traceback) from exc_value
   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
     return self.cursor.execute(sql, params)
   File "/usr/local/lib/python3.8/site-packages/mssql/base.py", line 567, in execute
     return self.cursor.execute(sql, params)
 django.db.utils.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The index 'transaction_transaction_conf_first_distribution_date_id_76f3b97f_uniq' is dependent on column 'conf_first_distribution_date_id'. (5074) (SQLExecDirectW)")
```

**Comment by absci** [comment] 2021-09-16 02:28
I can reproduce this error. I removed the index deletion because it's not recreated in some cases. I'll find a way to fix the RenameField.

**Comment by absci** [comment] 2021-12-21 23:10
The issue has been fixed now.

**Closed by absci** 2021-12-21 23:10 UTC
